Repository FalkorDB/falkordb-browser, pull requests merged in 2024-02, with the labels that each got.

#73 add dockerfile
  .env.local.template
  .github/workflows/nextjs.yml
  Dockerfile
  README.md
  next.config.js
Labels: size:M, lgtm

#75 fix #44 replace center icon
  app/graph/toolbar.tsx
  app/login/page.tsx
Labels: size:XS

#77 Fixes lowecase/uppercase graph name issue
  app/components/combobox.tsx
Labels: size:XS, lgtm

#79 fix #78 set responsive navbar and toolbar
  app/graph/query.tsx
  app/providers.tsx
  app/useScreenSize.ts
  package-lock.json
  package.json
Labels: size:L

#81 Add release pipeline
  .github/workflows/release-image.yml
Labels: size:M, lgtm

#83 fix #82 point the right org
  .github/workflows/release-image.yml
Labels: size:XS

#85 fix #84 update actions upgrade deprecated
  .github/workflows/release-image.yml
Labels: size:XS

#87 fix #86 add docker info and badges
  README.md
Labels: size:S

#90 ref #89 add node & edges properties
  app/graph/model.ts
  app/graph/page.tsx
Labels: size:M

#91 fix #45 set edge label color according to darkmode
  app/graph/page.tsx
Labels: size:L

#92 Label color
  app/graph/page.tsx
Labels: size:XS

#96 fix #42 hovering over a cell should show the content in tooltip
  app/graph/tableview.tsx
Labels: size:S, lgtm

#98 Update dependabot.yml add github-action
  .github/dependabot.yml
Labels: size:XS

#99 Menu color
  app/graph/toolbar.tsx
  components/custom/navbar.tsx
Labels: size:S, lgtm
