Repository FalkorDB/falkordb-browser, pull requests merged in 2024-01, with the labels that each got.

#49 fix #48 Collapse to toolbar
  app/providers.tsx
  components/custom/navbar.tsx
Labels: size:L

#53 add template .env.local
  .env.local.template
Labels: size:XS

#54 Update README.md - extend the getting started
  README.md
Labels: documentation, size:XS

#60 fix #59 add lint checks and clean clean errors
  .eslintrc.json
  app/api/auth/[...nextauth]/options.ts
  app/api/graph/[graph]/[node]/route.ts
  app/api/graph/route.ts
  app/details/DatabaseLine.tsx
  app/details/page.tsx
  app/graph/labels.tsx
  app/graph/model.ts
  app/graph/page.tsx
  app/graph/query.tsx
  app/graph/tableview.tsx
  app/graph/toolbar.tsx
  app/layout.tsx
  app/login/page.tsx
  app/providers.tsx
  components/custom/GithubMark.tsx
  components/custom/navbar.tsx
  lib/utils.ts
  package-lock.json
  package.json
Labels: size:L

#61 Alaminfix #50 add graphs list
  app/components/combobox.tsx
  app/details/DatabaseLine.tsx
  app/graph/GraphList.tsx
  app/graph/page.tsx
  app/graph/query.tsx
  components/ui/command.tsx
  components/ui/dialog.tsx
  components/ui/popover.tsx
  components/ui/separator.tsx
  package-lock.json
  package.json
Labels: size:XL

#63 Replaced Text as suggested
  app/page.tsx
  app/providers.tsx
Labels: size:XS, lgtm

#66 fix #35 Set Login page as child page
  app/graph/page.tsx
  app/login/page.tsx
  app/page.tsx
  app/providers.tsx
Labels: size:L

#68 fix #67 handle failed disconnection
  app/api/auth/[...nextauth]/options.ts
Labels: size:XS

#70 fix #69 verify a graph is selected from list on query
  app/graph/page.tsx
Labels: size:S

#72 fix #71 select last created graph
  app/graph/GraphList.tsx
Labels: size:XS
