Repository FalkorDB/falkordb-browser, pull requests merged in 2025-06, with the labels that each got.

#1006 Fix # 990 Enhance Graph query handling by adding profile support.
  app/api/graph/model.ts
  app/graph/GraphDataPanel.tsx
  app/graph/GraphDataTable.tsx
  app/graph/GraphView.tsx
  app/graph/MetadataView.tsx
  app/graph/Selector.tsx
  app/graph/page.tsx
Labels: Review effort 2/5

#1007 Fix #1003 pass a custom trigger to create graph in the tutorial
  app/graph/Tutorial.tsx
  e2e/logic/POM/tutorialPanelComponent.ts
  e2e/tests/tutorial.spec.ts
Labels: Review effort 1/5

#1011 Fix AI comments
  app/api/graph/model.ts
  app/components/ForceGraph.tsx
  app/components/Header.tsx
  app/components/graph/DeleteGraph.tsx
  app/graph/GraphDataPanel.tsx
  app/graph/Selector.tsx
  app/graph/page.tsx
  app/graph/toolbar.tsx
  app/schema/SchemaDataPanel.tsx
  app/schema/page.tsx
  app/settings/QuerySettings.tsx
Labels: Review effort 3/5

#1017 Update README.md
  README.md
Labels: Review effort 1/5

#1023 Fix # Update GraphDataPanel and SchemaDataPanel to include type check before displaying remove label/button options for edges.
  app/graph/GraphDataPanel.tsx
  app/schema/SchemaDataPanel.tsx
Labels: Review effort 1/5

#1018 Potential fix for code scanning alert no. 10: Workflow does not contain permissions
  .github/workflows/playwright.yml
Labels: Review effort 1/5

#1026 Fix #1025 Refactor MetadataView and Selector components to improve layout and spacing.
  app/graph/MetadataView.tsx
  app/graph/Selector.tsx
Labels: Review effort 2/5

#1032 Fix #1013 Add limit warnings
  app/api/graph/model.ts
  app/graph/GraphDetails.tsx
  app/graph/GraphView.tsx
  app/graph/View.tsx
  app/graph/page.tsx
  app/schema/page.tsx
  app/settings/QuerySettings.tsx
Labels: Review effort 3/5

#1036 Fix #1031, #1029 Update ForceGraph and TableComponent to improve responsiveness and add new entity type;
  app/components/ForceGraph.tsx
  app/components/TableComponent.tsx
  app/graph/GraphDetails.tsx
  app/graph/GraphView.tsx
  app/graph/MetadataView.tsx
  app/graph/TableView.tsx
  app/graph/selectGraph.tsx
Labels: Review effort 3/5

#1039 Update version to 1.4.1 in package.json and package-lock.json
  package-lock.json
  package.json
Labels: Review effort 1/5

#1041 Fix #994 Close dialogs on escape
  app/api/schema/[schema]/[node]/route.ts
  app/components/DialogComponent.tsx
  app/components/PaginationList.tsx
  app/components/TableComponent.tsx
  app/components/graph/DeleteGraph.tsx
  app/graph/GraphDataPanel.tsx
  app/graph/GraphDataTable.tsx
  app/graph/selectGraph.tsx
  app/schema/SchemaCreateElement.tsx
  app/schema/SchemaDataPanel.tsx
  app/schema/SchemaView.tsx
  app/schema/page.tsx
  app/settings/QuerySettings.tsx
  components/ui/table.tsx
Labels: Review effort 4/5

#1044 Add graph tests
  e2e/logic/POM/graphPage.ts
  e2e/tests/dataPanel.spec.ts
  e2e/tests/graph.spec.ts
Labels: Review effort 2/5

#1053 Fix #993 Add interaction to list through search input
  app/components/DialogComponent.tsx
  app/components/PaginationList.tsx
  app/components/TableComponent.tsx
  app/graph/GraphDataPanel.tsx
  app/graph/Selector.tsx
  app/graph/selectGraph.tsx
Labels: Review effort 4/5
