Repository FalkorDB/falkordb-browser, pull requests merged in 2025-08, with the labels that each got.

#1090 Revert "Fix # 1077 Enhance ForceGraph component with improved link rendering and hover e…"
  app/api/graph/[graph]/suggestions/route.ts
  app/components/ForceGraph.tsx
Labels: Review effort 2/5

#1086 Update readme
  README.md
Labels: Review effort 1/5

#1075 Fix #1074 Fix count in graph details
  app/components/EditorComponent.tsx
  app/graph/GraphDetails.tsx
  app/graph/GraphView.tsx
  app/graph/Selector.tsx
  app/graph/page.tsx
  app/schema/SchemaView.tsx
  app/schema/page.tsx
Labels: Review effort 3/5

#1089 Fix tls
  app/components/FormComponent.tsx
  app/login/LoginForm.tsx
Labels: Review effort 2/5

#1102 Update version to 1.4.3 in package.json and package-lock.json
  package-lock.json
  package.json
Labels: Review effort 1/5

#1103 Update ForceGraph component to center link labels by adjusting text c…
  app/components/ForceGraph.tsx
Labels: Review effort 2/5

#1117 Fix #1113 Fix delay in checkbox
  app/components/TableComponent.tsx
Labels: Review effort 2/5

#1116 FIx #1112 Refactor query history management to ensure unique queries in history…
  app/graph/Selector.tsx
  app/graph/page.tsx
Labels: Review effort 2/5

#1125 Refactor button styles in GraphInfoPanel for improved UI consistency …
  app/graph/graphInfo.tsx
Labels: Review effort 2/5

#1127 Update version to 1.4.5 in package.json and package-lock.json; refact…
  app/api/auth/[...nextauth]/options.ts
  package-lock.json
  package.json
Labels: Review effort 2/5

#1126 Staging
  app/api/auth/[...nextauth]/options.ts
  app/graph/graphInfo.tsx
  package-lock.json
  package.json
Labels: Review effort 2/5
