Repository FalkorDB/falkordb-browser, pull requests merged in 2025-03, with the labels that each got.

#778 fix jemini comments
  app/api/graph/config/[config]/route.ts
  app/api/graph/config/route.ts
  e2e/tests/preferences.spec.ts
Labels: Review effort 2/5

#781 Anchel123 patch 1
  README.md
Labels: Review effort 1/5

#798 Fix #794 Fix type error in meta data view
  app/graph/GraphView.tsx
  app/graph/page.tsx
Labels: Review effort 2/5

#799 Fix #793 Remove delete node when role is read only
  app/schema/SchemaDataPanel.tsx
Labels: Review effort 1/5

#811 Fix #788 Return undefined for empty data in TableView component to prevent ren…
  app/graph/TableView.tsx
Labels: Review effort 1/5

#812 Update package.json
  package-lock.json
  package.json
Labels: Review effort 1/5

#782 Staging
  README.md
  app/components/ui/combobox.tsx
  app/graph/GraphView.tsx
  app/graph/TableView.tsx
  app/graph/page.tsx
  app/schema/SchemaDataPanel.tsx
  package-lock.json
  package.json
Labels: Review effort 1/5

#800 Fix #790 Fix profile button
  app/graph/MetadataView.tsx
  app/graph/Selector.tsx
Labels: Review effort 2/5

#815 Fix #814 Change the tooltip on run query
  app/components/EditorComponent.tsx
Labels: Review effort 2/5

#819 Fix #814 Update tooltip text for the Run button in EditorComponent for improve…
  app/components/EditorComponent.tsx
Labels: Review effort 1/5

#820 Update package.json
  package-lock.json
  package.json
Labels: Review effort 1/5

#823 Fix #816 Refactor utility functions and add new Metadata classes. Update tests…
  e2e/infra/utils.ts
  e2e/logic/POM/graphPage.ts
  e2e/logic/POM/metadataView.ts
  e2e/logic/POM/preferencesView.ts
  e2e/tests/metadata.spec.ts
  e2e/tests/preferences.spec.ts
Labels: Review effort 3/5

#826 Update package.json
  package-lock.json
  package.json
Labels: Review effort 1/5
