Repository FalkorDB/falkordb-browser, pull requests merged in 2025-04, with the labels that each got.

#829 Fix #827 Add onExpand call in ForceGraph component to reset selection state
  app/components/ForceGraph.tsx
Labels: Review effort 1/5

#830 Fix #828 Refactor GraphDataPanel to manage state more effectively by using use…
  app/graph/GraphDataPanel.tsx
Labels: Review effort 2/5

#832 Fix #681 Fix editor full screen
  app/components/CloseDialog.tsx
  app/components/EditorComponent.tsx
  app/components/ui/Button.tsx
Labels: Review effort 2/5

#831 Fix #705 Add pulling to run query
  .env.local.template
  app/api/auth/[...nextauth]/options.ts
  app/api/graph/[graph]/[node]/label/route.ts
  app/api/graph/[graph]/[node]/route.ts
  app/api/graph/[graph]/count/route.ts
  app/api/graph/[graph]/query/route.ts
  app/api/graph/[graph]/route.ts
  app/api/graph/[graph]/suggestions/route.ts
  app/api/graph/config/route.ts
  app/api/graph/model.ts
  app/api/graph/route.ts
  app/api/schema/[schema]/[node]/label/route.ts
  app/api/schema/[schema]/[node]/route.ts
  app/api/schema/[schema]/count/route.ts
  app/api/schema/[schema]/route.ts
  app/api/schema/route.ts
  app/components/CreateGraph.tsx
  app/components/EditorComponent.tsx
  app/components/ForceGraph.tsx
  app/graph/GraphDataPanel.tsx
  app/graph/GraphView.tsx
  app/graph/Selector.tsx
  app/graph/page.tsx
  app/schema/SchemaDataPanel.tsx
  app/schema/SchemaView.tsx
  app/schema/page.tsx
  lib/utils.ts
  package-lock.json
  package.json
Labels: Review effort 4/5

#779 Expand test coverage
  .github/workflows/playwright.yml
  app/graph/GraphDataPanel.tsx
  app/graph/GraphView.tsx
  app/graph/Selector.tsx
  app/graph/page.tsx
  e2e/config/constants.ts
  e2e/config/queries.json
  e2e/infra/ui/basePage.ts
  e2e/infra/utils.ts
  e2e/logic/POM/dataPanelComponent.ts
  e2e/logic/POM/graphPage.ts
  e2e/logic/POM/navBarComponent.ts
  e2e/logic/POM/preferencesView.ts
  e2e/logic/POM/queryHistoryComponent.ts
  e2e/logic/POM/settingsConfigPage.ts
  e2e/logic/POM/settingsUsersPage.ts
  e2e/logic/api/apiCalls.ts
  e2e/tests/canvas.spec.ts
  e2e/tests/dataPanel.spec.ts
  e2e/tests/graph.spec.ts
  e2e/tests/metadata.spec.ts
  e2e/tests/preferences.spec.ts
  e2e/tests/queryHistory.spec.ts
  e2e/tests/settingsConfig.spec.ts
  e2e/tests/settingsUsers.spec.ts
  playwright.config.ts
Labels: Review effort 2/5

#841 schema tests
  app/graph/labels.tsx
  app/schema/SchemaCreateElement.tsx
  app/schema/SchemaDataPanel.tsx
  app/schema/page.tsx
  e2e/config/urls.json
  e2e/infra/utils.ts
  e2e/logic/POM/graphPage.ts
  e2e/logic/POM/loginPage.ts
  e2e/logic/POM/schemaPage.ts
  e2e/logic/api/apiCalls.ts
  e2e/logic/api/responses/getSchemaResponse.ts
  e2e/tests/auth.setup.ts
  e2e/tests/graph.spec.ts
  e2e/tests/schema.spec.ts
Labels: Review effort 2/5
