Repository FalkorDB/falkordb-browser, pull requests merged in 2025-09, with the labels that each got.

#1150 Add Login for Rest Api
  app/api/auth/[...nextauth]/options.ts
  app/api/auth/login/route.ts
  package-lock.json
  package.json
Labels: Review effort 2/5

#1163 Fix #1147 fix tutorial
  app/graph/Tutorial.tsx
  app/graph/page.tsx
  app/providers.tsx
Labels: Review effort 2/5

#1164 Update version to 1.4.7 in package.json and package-lock.json
  package-lock.json
  package.json
Labels: Review effort 1/5

#1165 Resolve AI comments
  app/components/Header.tsx
  app/graph/Tutorial.tsx
  public/icons/Discord-dark.svg
  public/icons/Discord-light.svg
  public/icons/Discord.svg
Labels: Review effort 1/5

#1171 Fix #1169 Make graph info resizable
  app/api/graph/model.ts
  app/components/EditorComponent.tsx
  app/components/ForceGraph.tsx
  app/components/Header.tsx
  app/components/PaginationList.tsx
  app/components/TableComponent.tsx
  app/globals.css
  app/graph/Chat.tsx
  app/graph/GraphDataTable.tsx
  app/graph/MetadataView.tsx
  app/graph/Selector.tsx
  app/graph/TableView.tsx
  app/graph/graphInfo.tsx
  app/graph/labels.tsx
  app/graph/page.tsx
  app/graph/selectGraph.tsx
  app/providers.tsx
  app/settings/browserSettings.tsx
  public/fonts/FiraCode.ttf
  public/fonts/SofiaSans.ttf
Labels: Review effort 3/5

#1167 Add auth support for api endpoints
  app/api/auth/[...nextauth]/options.ts
  app/api/auth/login/route.ts
  package-lock.json
  package.json
Labels: Review effort 3/5

#1173 Fix # Add timestam and graph name to query
  app/api/graph/model.ts
  app/components/PaginationList.tsx
  app/components/TableComponent.tsx
  app/components/provider.ts
  app/globals.css
  app/graph/Selector.tsx
  app/graph/selectGraph.tsx
  app/providers.tsx
  e2e/logic/POM/queryHistoryComponent.ts
  e2e/tests/queryHistory.spec.ts
Labels: Review effort 3/5
