Repository FalkorDB/falkordb-browser, pull requests merged in 2025-07, with the labels that each got.

#1062 Fix # 1060 Remove "/" before query params
  app/api/graph/[graph]/count/route.ts
  app/api/schema/[schema]/count/route.ts
  app/components/EditorComponent.tsx
  app/components/graph/DuplicateGraph.tsx
  app/graph/page.tsx
  app/graph/selectGraph.tsx
  app/schema/page.tsx
  e2e/logic/api/apiCalls.ts
Labels: Review effort 2/5

#1055 Fix #1016, #952 Fix performance
  .eslintignore
  app/components/ForceGraph.tsx
  app/components/TableComponent.tsx
  app/graph/GraphDetails.tsx
  app/graph/GraphView.tsx
  app/graph/Selector.tsx
  app/graph/controls.tsx
  app/graph/page.tsx
  app/graph/toolbar.tsx
  app/schema/SchemaView.tsx
  app/schema/page.tsx
  components/ui/table.tsx
  e2e/logic/POM/graphPage.ts
  e2e/logic/POM/settingsUsersPage.ts
  e2e/tests/canvas.spec.ts
  e2e/tests/dataPanel.spec.ts
  e2e/tests/graph.spec.ts
  e2e/tests/queryHistory.spec.ts
  e2e/tests/settingsQuery.spec.ts
Labels: Review effort 4/5

#1068 fix ai comments
  e2e/logic/POM/graphPage.ts
  e2e/logic/POM/loginPage.ts
  e2e/logic/POM/settingsQueryPage.ts
  e2e/tests/cluster.spec.ts
  e2e/tests/settingsQuery.spec.ts
Labels: Review effort 2/5

#1069 fix AI comments
  app/components/graph/DeleteGraph.tsx
  app/graph/page.tsx
  app/schema/SchemaCreateElement.tsx
  app/schema/SchemaDataPanel.tsx
  app/schema/page.tsx
  e2e/logic/POM/graphPage.ts
  e2e/tests/canvas.spec.ts
  package-lock.json
  package.json
Labels: Review effort 2/5

#1072 upgrade canvas performance
  app/components/ForceGraph.tsx
  e2e/logic/POM/graphPage.ts
  e2e/tests/canvas.spec.ts
Labels: Review effort 2/5

#1073 fix canvas tests
  .gitignore
  e2e/logic/POM/graphPage.ts
  e2e/tests/canvas.spec.ts
Labels: Review effort 2/5

#1076 Fix #1059 Upgrade falkordb dependency to version 6.3.0 in package.json and pack…
  package-lock.json
  package.json
Labels: Review effort 1/5

#1078 Fix # 1077 Enhance ForceGraph component with improved link rendering and hover e…
  app/api/graph/[graph]/suggestions/route.ts
  app/components/ForceGraph.tsx
Labels: Review effort 3/5
